language: node_js
branches:
  only:
    - master
node_js:
  - 14
os:
  - osx
osx_image: xcode11.3
before_install:
  - brew reinstall gettext
  - brew unlink gettext && brew link gettext --force
  - npm config set unsafe-perm=true
install:
  - npm install
script:
  - rm -rf electron/electron-resources/license*
  - chmod +x macos-signing.sh
  - ./macos-signing.sh
  - npm run publish
