version: "{build}"
branches:
  only:
    - master
skip_non_tags: false
clone_depth: 1
environment:
  nodejs_version: "14"
  BONJOUR_SDK_HOME: "C:\\Program Files\\Bonjour SDK"
  BONJOUR_SDK_DOWNLOAD:
    secure: 1uWToJLKf6uUn0/fsVHbrRSHDDgyxJ9KgD4cslGCqmz486RoS5levXRMLCKm3E7flrnyhSXcUWFHK9KcUxPlO2LYHYRVR+OGkndJ0fbrxhY=
image: Visual Studio 2017
install:
  - ps: Install-Product node $env:nodejs_version x64
  - set PATH=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.4;%PATH%
  - python --version
  - appveyor DownloadFile https://github.com/snackmix/barcode-to-pc-server/raw/master/electron/electron-resources/Bonjour64.msi
  - msiexec /i Bonjour64.msi /qn
  - del Bonjour64.msi
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  - ps: $package_json = Get-Content -Raw -Path .\electron\package.json
  - ps: $package_json = $package_json -replace ".*certificateSha1.*\r?\n" -replace ",(?=\r?\n\W+})"
  - ps: $package_json_path = (Get-Item -Path "." -Verbose).FullName + "\electron\package.json"
  - ps: $Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
  - ps: "[System.IO.File]::WriteAllLines($package_json_path, $package_json, $Utf8NoBomEncoding)"
  - git config --global user.email "build@github.com"
  - git config --global user.name "Build User"
  - npm cache verify
  - cd electron
  - npm ci --unsafe-perm
  - set NODE_ENV=production
  - set ECHO=ON
  - echo "%PATH%"
  - echo "%NODE_ENV%"
  - node --version
  - npm --version
build_script:
  - cmd: npm run build
artifacts:
  - path: \electron\dist\nsis-web
    name: barcode-to-pc-server.offline-installer
    type: zip
test: off
